### PR TITLE
Fix http config

### LINKED ISSUE #24: load http whitelist and blacklist from config file
## Useful information to include:
 - Minecraft version: 1.16.2
 - CC: Tweaked version: 1.91.2
 - Detailed reproduction steps: 
1. open a new world
1. place a computer
1. run `lua`
1. run `http.checkURL("http://localhost")`
1. - Result: "Domain not permitted"
1. go to `<intall_root>/config/computercraft.json5`
1. remove all elements from the blacklist
1. add localhost to whitelist
1. restart Minecraft
1. re-do steps `3` and `4`
1. Result unchanged (`5`)

## Probable cause :
I've spent a few minutes looking at the code and what I believe to be the issue is that this
https://github.com/Zundrel/cc-tweaked-fabric/blob/4d00969ef0a6907e122789995ae36fa10070ccb3/src/main/java/dan200/computercraft/shared/util/Config.java#L162-L165
Enables the updating of the whitelist and blacklist, however (I think) the URLs are checked against the `httpRules`
https://github.com/Zundrel/cc-tweaked-fabric/blob/4d00969ef0a6907e122789995ae36fa10070ccb3/src/main/java/dan200/computercraft/ComputerCraft.java#L89-L95
which are not re-created when the blacklist and whitelist arrays are updated.

I'm happy to help if you need more information.

### PR DESCRIPTION
**Pull request by techninja1008**
Fixes #24. This essentially implements the suggested fix described in that issue. Upstream has done it slightly differently however, but that would entail drastically changing the current way that the whitelist/blacklist is configured. If/when we want to do that in the future, this fix is designed to easily accommodate that.

### CODE REVIEW

**Comment by techninja1008** [comment]
This has been tested.

**Comment by techninja1008** [comment]
Force-pushed to remove unrelated commit from #26

**Review by Shrimpstress — APPROVED** [review]
Everything looks good to me. Is this ready for merge?

Edit: I would also like to mention that I've given you collaborator access to the GitHub repo. You're by no means obligated to fix further issues, although if you'd like you're certainly free to do so. Time constraints as of late have had this fairly low priority on my list of projects, so I just haven't gotten around to fixing up the issues we currently have.

**Comment by techninja1008** [comment]
Yep, I've tested this pretty extensively on my survival world. I totally understand the whole time constraints thing - I often find it difficult to find time for various projects I want to do some work on.

**Pull request merged**
