### PR TITLE
yes

### PR DESCRIPTION
**Pull request by nullified33**
## A quick checklist
 - If there's a existing issue, please link to it. If not, provide fill out the same information you would in a normal issue - reproduction steps for bugs, rationale for use-case.
 - If you're working on CraftOS, try to write a few test cases so we can ensure everything continues to work in the future. Tests live in `src/test/resources/test-rom/spec` and can be run with `./gradlew check`.

### CODE REVIEW

**Comment by Ueaj-Kerman** [comment]
u forgot to replace some of the CC:R names with CC:T

**Comment by toad-dev** [comment]
Wouldn't this work better as a resource pack? Then people could choose which textures they wanted to play with, and you wouldn't have to keep a fork of the code up to date.

**Comment by Ueaj-Kerman** [comment]
wdym

**Comment by Ueaj-Kerman** [comment]
are the textures from upstream or custom

**Comment by toad-dev** [comment]
It's a custom texture set.

**Comment by Ueaj-Kerman** [comment]
ah ok, that should be done as a texturepack then

**Comment by nullified33** [comment]
> ah ok, that should be done as a texturepack then

Yeah there is a texture pack version

**Comment by nullified33** [comment]
I’ll fix images later for now I’ll rebrand with a new branch

**Comment by nullified33** [comment]
https://github.com/Merith-TK/cc-restitched/commit/d8b0037cfa69887eeef54562d6b1886bc0093640
Are all the files you need to edit.

**Comment by nullified33** [comment]
Excluding images

**Review by Ueaj-Kerman — CHANGES_REQUESTED** [review]
what does this PR do other than change the textures which still needs to be changed

**Comment by nullified33** [comment]
> what does this PR do other than change the textures which still needs to be changed

thats it

**Comment by nullified33** [comment]
> what does this PR do other than change the textures which still needs to be changed

sorry

**Pull request closed without merging**
