### PR TITLE
Change turtle block breaking to call onBreak

### LINKED ISSUE #25: turtle disappears when mined by another turtle
minecraft version:fabric 1.16.4
cc:T version:1.91.2

if one turtle digs another, the latter does not go into the inventory or fall on the ground.it just  disappears

### PR DESCRIPTION
**Pull request by techninja1008**
Fixes #25.

Specifically, this changes the first call of `Block.onBroken` to `Block.onBreak`, to make the logic consistent with `ServerPlayerInteractionManager`.

### CODE REVIEW

**Comment by Ueaj-Kerman** [comment]
has this been tested, if so, thank you for your work

**Comment by techninja1008** [comment]
It has, turtles can now break and pick up other turtles and computers successfully

**Comment by Ueaj-Kerman** [comment]
I'll merge your pull request, are you planning on making any more soon or should I publish a release on the curseforge

**Comment by techninja1008** [comment]
I'm currently in the process of a fix for #24

**Comment by Ueaj-Kerman** [comment]
that was fixed upstream I think, might be best to go off of that

**Comment by Ueaj-Kerman** [comment]
do you want to be added to the repository?

**Comment by techninja1008** [comment]
If you want, yeah. I will put it out there that this is my first experience with Fabric, although I've done Forge modding and other java (and scala) work as well.

**Comment by Ueaj-Kerman** [comment]
that's fine

**Comment by techninja1008** [comment]
Didn't realize renaming the branch would close this PR, see #28

**Pull request closed without merging**
