### PR TITLE
Assorted bug fixes.

### PR DESCRIPTION
**Pull request by toad-dev**
# Bug fixes

- `turtle.drop()` sees connected double chest inventories properly.
- `turtle.drop()` works with composters.
- `turtle.place()` allows bone meal usage.
- `turtle.place()` allows setting sign text.
- `turtle.place()` allows feeding passive mobs.
- `ModelTransformer` works and allows turtle tools to be rendered in GUI properly. (I think the vertex format changed underneath the old code or something? If it changes again things might break, but for now it renders properly in at least vanilla and sodium.)

## Cleanup

- Generic peripheral inventory methods now use the `ItemStorage` utility wrapper like other parts of the code base. I didn't see that last time and made a mess re-inventing the wheel.
- Removed GitHub actions that weren't passing because they expected the forge repository's environment.

### CODE REVIEW

**Comment by toad-dev** [comment]
I'm not sure how to fix that luaJavaDoc check. I think the build action expects a different gradle config than what's in the repo?

**Comment by SquidDev** [comment]
Yep. It's probably worth rolling back https://github.com/Zundrel/cc-tweaked-fabric/commit/457a863842ee4a7b2726a872abbe1b85fa41b4da, or at least lines 35-40 of the `main-ci.yml` file.

**Comment by toad-dev** [comment]
When a test fails -> backspace key

**Comment by Ueaj-Kerman** [comment]
looks good

**Pull request merged**
